DataRoot: /data1/data_here
VideoList:
#  - '01'
#  - '02'
#  - '03'
#  - '04'
  - '05'
#  - '06'
VideoName:
  - 'San Francisco, USA'
  - 'Delna, Libya'
  - 'Adana, Turkey'
  - 'Minneapolis, USA'
  - 'Minneapolis, USA'
  - 'Muharraq, Bahrain'

AnnosDirName: annotations
SeqDirName: sequences
AttrPostfix: .attr
StatePostfix: .state
RectPostfix: .rect
PolyPostfix: .poly
AbsPostfix: .abs

AttrsCH:
  - '短时遮挡：出现过遮挡帧数不超过50帧的短时遮挡现象至少1次'
  - '长时遮挡：出现过遮挡帧数超过50帧的长时遮挡现象至少1次'
  - '*相似干扰：在被跟踪目标周围[目标大小的2.5倍范围内]出现至少一个相似目标' # 确定一个范围2.5
  - '*亮度变化：出现过目标亮度或颜色发生明显的变化的现象至少1次'
  - '*目标背景变化：目标周围道路出现阴影或地面颜色变化'
  - '慢速运动：目标运动速度低于每秒1个像素'     # X有待确定
  - '*自然干扰：云雾遮挡，雾霾，画面抖动，影像模糊'
  - '连续遮挡：出现过2次或2次以上长短时遮挡'
  - '背景相似：目标与背景融为一体，且无明显遮挡物'
  - '*平面内旋转：在平面内旋转，车辆发生大于30（马路口，环岛，匝道等）'

AttrsEN:
  - '[STO] Short-Term Occlusion'
  - '[LTO] Long-Term Occlusion'
  - '[DS] Dense Similarity'
  - '[IV] Illumination Variation'
  - '[BCH] Background Change'
  - '[SM] Slow Motion'
  - '[ND] Natural Disturbance'
  - '[CO] Continuous Occlusion'
  - '[BCL] Background Cluster'
  - '[IPR] In-Plane Rotation'