ResultDir: '/data1/tracking_results/all_new_result_jilin'
SubDir: 'unsupervised'
ResultFileNamePostfix: '001'
#SubDir: 'unsupervised_shake'

Trackers:
  'KeepTrack': 'KeepTrack'
  'KeepTrack_fast': 'KeepTrack$_{Fast}$'
  'StackSt101': 'Stark$_{ST101}$'
  'StackSb': 'Stark$_{S50}$'
  'StackSt': 'Stark$_{ST50}$'
  'SiamGAT': 'SiamGAT$_{OTB-UAV123}$'
  'SiamGAT_lasot': 'SiamGAT$_{LaSOT}$'
  'SiamGAT_got10k': 'SiamGAT$_{GOT10k}$'
  'SiamGAT_trackingnet': 'SiamGAT$_{TrackingNet}$'
  'TransT': 'TransT'
  'TrDiMP': 'TrDiMP'
  'TrSiam': 'TrSiam'
  'TrTrOnline': 'TrTr$_{Online}$'
  'TrTr': 'TrTr'
  'DCFST': 'DCFST'
  'KYS': 'KYS'
  'CGACD': 'CGACD$_{VOT}$'
  'CGACD_otb': 'CGACD$_{OTB}$'
  'd3s': 'D3S'
  'OceanG': 'Ocean$_G$'
  'OceanL': 'Ocean$_L$'
  'OceanO': 'Ocean$_O$'
  'OceanOTBOnline': 'Ocean$_{OTBOnline}$'
  'OceanV': 'Ocean$_V$'
  'OceanVOTOnline': 'Ocean$_{VOTOnline}$'
  'SuperDiMP': 'SuperDiMP'
  'PrDiMP18': 'PrDiMP18'
  'PrDiMP': 'PrDiMP50'
  'SiamRCNN': 'Siam R-CNN'
  'siamattn_otb': 'SiamAttn$_{OTB}$'
  'siamattn': 'SiamAttn'
  'siamban_otb': 'SiamBAN$_{OTB}$'
  'siamban': 'SiamBAN'
  'SiamCAR': 'SiamCAR'
  'siamfcpp_alexnet-got': 'SiamFC++$_{AlexGOT}$'
  'siamfcpp_alexnet-got-online': 'SiamFC++$_{AlexGOTOnline}$'
  'siamfcpp_alexnet_online': 'SiamFC++$_{AlexOnline}$'
  'siamfcpp_alexnet-otb': 'SiamFC++$_{AlexOTB}$'
  'siamfcpp_alexnet-uav123': 'SiamFC++$_{AlexUAV123}$'
  'siamfcpp_alexnet_votlt': 'SiamFC++$_{AlexVOTLT}$'
  'siamfcpp_alexnet': 'SiamFC++$_{Alex}$'
  'siamfcpp_googlenet-got': 'SiamFC++$_{GoogLeGOT}$'
  'siamfcpp_googlenet-lasot': 'SiamFC++$_{GoogLeLaSOT}$'
  'siamfcpp_googlenet-otb': 'SiamFC++$_{GoogLeOTB}$'
  'siamfcpp_googlenet-trackingnet': 'SiamFC++$_{GoogLeTrackingNet}$'
  'siamfcpp_googlenet-trackingnet-fulldata': 'SiamFC++$_{GoogLeTrackingNetFull}$'
  'siamfcpp_googlenet-uav123': 'SiamFC++$_{GoogLeUAV123}$'
  'siamfcpp_googlenet_votlt': 'SiamFC++$_{GoogLeVOTLT}$'
  'siamfcpp_googlenet': 'SiamFC++$_{GoogLe}$'
  'siamfcpp_shufflenetv2x0_5-got': 'SiamFC++$_{Shuff05}$'
  'siamfcpp_shufflenetv2x1_0-got': 'SiamFC++$_{Shuff10}$'
  'siamfcpp_tinyconv': 'SiamFC++$_{Tinyconv}$'
  'DiMP18': 'DiMP18'
  'DiMP': 'DiMP50'
  'ATOM': 'ATOM'
  'SiamDW_fc': 'SiamDW$_{FC}$'
  'SiamDW_rpn': 'SiamDW$_{RPN}$'
  'siammask_davis': 'SiamMask$_{DAVIS}$'
  'siammask_vot': 'SiamMask$_{VOT}$'
  'siammask': 'SiamMask'
  'SiamRPNppAlex': 'SiamRPN++$_{Alex}$'
  'SiamRPNppMobile': 'SiamRPN++$_{Mobile}$'
  'SiamRPNppLt': 'SiamRPN++$_{LT}$'
  'SiamRPNpp': 'SiamRPN++'
  'siammask_e': 'SiamMask-E'
  'RT_MDNet': 'RT-MDNet'
  'DaSiamRPNPython': 'DaSiamRPN'
  'ECO': 'ECO'
  'MDNet': 'MDNet'
  'KCF': 'KCF'
  'ECO-H': 'ECO-H'
  'MCCT-H': 'MCCT-H'
  'MOSSE': 'MOSSE'
