video_seq: '04.000028'
frame_index: [1, 10, 240, 430, 520, 600, 640, 700]
scale: 10.0
win_width: 500
win_height: 500
show_attrs: true
show_frame_num: true
show_gt: true
save_ori: /data1/show_ori/test4.tiff