VideoFilePath: '/data/new_satellite_video/JL103B_MSS_20181109144154_迪拜国际机场.avi'
ImageSequence: '.tiff'
SaveToDirectory: 'data_cache'

CacheDirectory: 'data_cache/tmp'
CacheImage: '.tiff'

SelectArea: [100,100,400,400]
#AreaFormat: 'xywh'
WindowSize: [800, 600]  # 最小 500 x 500

VideoFormat: ['.mp4', '.MP4', '.avi', '.AVI']
ErrorFrame: 'skip'   # skip, interpolation, stop
