VideoFilePath: '/data1/ORSV/part2/ori/JL103B_MSS_20180104153259_100003219_102_001_L1B_MSS.avi'
ImageSequence: '.tiff'  # 如果上面的路径是视频文件，则该项无效
SaveToDirectory: 'annotations'    # 标注数据将保存在该文件夹中annotations文件夹内，其他辅助数据将存放在此路径
TargetFolderName: 'targets'   # 存放标注目标的文件夹

SelectArea: [4000,4000,6000,5000]   # x,y, xx ,yy
AnnotatorWinHeight: 600
AnnotatorWinWidth: 1200
TargetClasses:
  - ['vehicle', [255, 0, 0]]
  - ['large-vehicle', [0, 255, 0]]
  - ['ship', [0, 0, 255]]
  - ['airplane', [255, 255, 0]]
  - ['train', [255, 0 ,255]]

CacheDirectory: 'tmp'
CacheImage: '.tiff'

WindowSize: [1200, 600]  # 主界面的窗口尺寸，不要修改

VideoFormat: ['.mp4', '.MP4', '.avi', '.AVI']
ErrorFrame: 'skip'   # skip, interpolation, stop

# Frame Settings
StartScale: 1.0
ScaleList: null

AutoSaving: 10000 # 自动保存间隔的毫秒数 1秒 = 1000毫秒，如果设置为0或小于0的数则取消自动保存（手动保存模式需要手动按保存按键或退出的时候自动保存）


